#!/usr/bin/perl 

# ok i want an 8MB video file for output on discord.  so this is just another ffmpeg wrapper

# vp9 is the default.  yes it is slow.
# the program assumes you want 80-95kbps audio, then you pass the target size in megabytes (-m options) and it calcuates the streaming bit rate for the video.


# alt for metadata:
# https://metacpan.org/release/FFprobe/source/lib/FFprobe.pm

#   This script scales an input video to be the duration provided.  https://gist.github.com/Wollw/3943863


use Getopt::Long; 
use v5.10; 
use strict;use warnings;



=head1 SYNOPSIS

8mbwebm [options] inputfile...

 Options:
   -h, -help            brief help message
   -p, -pre		set prefix. "8MB_" is the default.
   -ss 			start time
   -to 			end time
   -s, -size		new size like: 640x480 (WIDTHxHEIGHT)
   			    if you like, you can omit one of the 
			    dimensions, like -s 640x or -s x480 
   -m 			change size in megabytes for output file
   -f 			go fast. ( -fast selects x264 )
   -264, -2 		output in mp4 (aac + H.264) 
  			     ( libx264 + libfdk_aac in ffmpeg) 
   -d 			specify output directory instead of dir of file
   -mono		downmix to output mono.
   -get-fps 		print FPS and exit
   -lower-fps 		reduce FPS by a ratio like 3:2
   			e.g. to reduce 25%, use: -lower-fps '4:3' 
   -get-duration        print duration in SSSS.ms for each video and exit
default -codec is opus + vp9  ( libvpx-vp9, libopus in ffmpeg) 

=cut


my $progname = '8mbwebm';
use Getopt::Long;
my $help;
my $outname;
my $prefix='8MB_';
my @realtime = ( '-deadline','realtime', '-cpu-used','4');  # 5 is 3x more quicker than 4, but hey it's working
my $realtime;
my $size ;
my $megabytes=8;
my $h264; 
my $outdir; 
my $preset='slow';
my $mono;
my $get_fps; 
my $lower_fps;
my $only_get_duration;

my ($ss, $to);
GetOptions ('lower-fps=s',\$lower_fps, 'get-fps',\$get_fps,'get-duration',\$only_get_duration, '-mono',\$mono, '-fast',\$preset, 'f', \$preset, 'd=s',\$outdir,'h264',\$h264,'x264',\$h264,  '2',\$h264, '264', \$h264, 'm=f', \$megabytes, 'ss=s', \$ss, 'to=s',\$to, 'size=s',\$size, 's=s', \$size,  'p=s',\$prefix,'pre=s',\$prefix, 'o=s',\$outname, 'h', \$help,'help', \$help) || do { print STDERR "$0 found invalid option\n";exit 1};

say("$progname. Convert any video file to an 8MB .webm"),  Getopt::Long::HelpMessage if $help;
sub check_exists_command { 
	my $check = `sh -c 'command -v $_[0]'`; 
	return $check;
}
check_exists_command 'ffmpeg' or die "$0 requires ffmpeg";
check_exists_command 'mediainfo' or die "$0 requires mediainfo";
# hmm ffprobe https://superuser.com/questions/841235/how-do-i-use-ffmpeg-to-get-the-video-resolution

@realtime = () if !$realtime;
my $multi_pass = !scalar@realtime;

$h264 = 1 if $preset ne 'slow';  # setting preset always implies x264 mode. 
$preset = 'fast' if $preset eq "1";

my @ss  =  ('-ss', $ss); @ss = () unless $ss;
my @to =   ('-to', $to); @to = () unless $to; 
my @mono =   ('-ac', 1); @mono = () unless $mono; 

die 'not a directory' if $outdir and ! -d $outdir;
die 'directory not writable' if $outdir and ! -w $outdir;


sub count_lines_in_string { 
	$_ = shift;
	return 0 if( !defined $_ or $_ eq "");
	my $lastchar = substr $_, -1,1;
	my $numlines = () = /\n/g;
	return $numlines + ($lastchar ne "\n") # was last line wasn't a whole line with a "\n";
}
#:enew
#:r !mediainfo --Info-Parameters
sub quoteforshell {  #adds single quotes i guess it could work like bash's printf %q
# doesn't relly return an array, just a single string
# so you pass multiarguments, and it quotes each one, separated by a space.
#s///gr is return sub, but leave orig untouched
  return join ' ', map
      "'" . s/'/'\\''/gr . "'", @_;
}
sub callmediainfov3 { # can return multiple thingies.
	# basically ( file, group, fields...) 
	my $file  = shift; 
	my $group = shift; 
	my $field;
	my $query;
"For Multiple stream kind, you can't use the command line directly (\nVideo is recognized as the continuity of the General definition, with a line break in the general stream info)"//0; # this means, to get one info from General, then one from video, you'd have to create a temp file, or call mediainfo several times. 
	$query = "$group;";
	while( $field = shift) {
		$query .="%$field%\\n"; 
	}
	$file = quoteforshell $file; 
	my $res = `mediainfo --Inform="$query" $file`;
	return split "\n", $res;
}

sub callmediainfov2   {  # uh prototypes suck
	my $file  = shift; 
	my $group  = shift; # like General
	my $field  = shift;
	$file = quoteforshell $file; 
	if ($field) {
		$_ = `mediainfo   --Inform="$group;%$field%"  $file `;
	} else {
		$_ = `mediainfo   --Inform="$group;"  "$file" `;
	}
	my $numlines = count_lines_in_string $_; 
	die 'too many lines mediainfo'. "$file $group $field"  if $numlines> 1; 

	chomp;$_}
if ($get_fps) {
	for my $file (@ARGV) { 
# should probably be single lines without any filenames.  I can see how people could use this to programatically get FPS or resolution. 
		say "$file: ${\callmediainfov2 $file,'General','FrameRate/String'}" ;
	}
	say 'normal exit.'; exit;
	say "$_: " for @ARGV; say 'normal exit.'; exit;
}
sub callmediainfov :prototype($$)  {  # uh prototypes suck
	$a=shift;
	$b=shift;
	$_ = `mediainfo   --Inform="Video;%$b%"  "$a" `;chomp;$_}
sub mb () { 2 ** 20}
my $inflation= (1.027 + .011);  # .4% container overhead webm
REDO:
my $eight = int($megabytes *mb / $inflation) ;  # divide... so target is smaller 
$eight *= 8; 
my $k = 1000;  # ffmpeg kbps is 1000, not 1024

sub to_seconds{
	my $has_ms = scalar $_[0] =~ /\.\d+/;

        my @components = split /[;:\.]/, $_[0];
	push @components, 0 if not $has_ms ; 

	@components = reverse @components;

	push @components, 0 if $#components < 3 ; # hours are opt.
	push @components, 0 if $#components < 3 ; # minutes are opt. 

# now we should have an array of ms, s, min, h. 

     	return (($components[3] * 60 + $components[2]) * 60 + $components[1])        + ".$components[0]";
#     	return (($components[3] * 60 + $components[2]) * 60 + $components[1]) * 1000 + ".$components[0]" * 1000;
}
sub to_seconds_conditional {
	$_ = shift;
	return to_seconds $_ if /[;:]/; # handle either case if time string  is 12.9 or 33:00.23
	return $_;
}

# this whole thing, validate the option looks like '4:3' or '3:4'
# then turn $lower_fps into a floating point number. 
if ($lower_fps) {
	my @num = sort { $a <=> $b} ($lower_fps =~  /(.*):(.*)/g);
	use Scalar::Util 'looks_like_number'; 
	( looks_like_number($_) or die 'found a non-number on option -lower-fps ') for @num;	
	die 'ratio not found on option -lower-fps' if $#num != 1; 
	$lower_fps = $num[0] / $num[1]; 
}

# setup a filename for temporary file for ffmpegs -passlogfile
our $logfile; 
# cleanup passlogfile if it was set. 
sub clenup { unlink $h264? ("$logfile-0.log.mbtree","$logfile-0.log") :"$logfile-0.log"  if $logfile; }
END { clenup };  
sub setlog {
	unlink $h264?  ("$logfile-0.log.mbtree","$logfile-0.log") :"$logfile-0.log"  if $logfile && -e $logfile; # output dir can change, so cleanup on every call. 
	my $file = shift;
	use File::Spec::Functions "splitpath";
	use File::Temp; 
	my $tempdir = $outdir? $outdir:(splitpath $file)[1];
	$tempdir = '.' if $tempdir eq "";
	$logfile = File::Temp::tempnam($tempdir , '8mbwebm_temp_'); 
}
my @mux_fix = split ' ', '-max_muxing_queue_size 9999';

for my $file (@ARGV) { 
	my (@fps);
	my $ms = callmediainfov2 $file, 'General', 'Duration';
	say("$progname fatal error: couldn't get duration of $file"), exit 1 unless $ms ;

	if ($only_get_duration) { 
		say $ms/1000;
		next;
	}

	if($lower_fps) {
		my $fps = callmediainfov2 $file, 'General', 'FrameRate';
		say("$progname fatal error: couldn't get FPS of $file"), exit 1 unless $fps ;
		$fps *= $lower_fps;
		@fps = ( '-r', $fps);
	}

#	use DDP; sub pp { p @_ };
	my @e = 'commandline.pl'; @e = (); 
# handle partial size like x480 or 640x 
	if ( $size and ! scalar $size =~ /\d+\D\d+/) {
		my @p_size = callmediainfov3 $file, 'Video',"Height","Width" ;    
		if(2 != @p_size) { 
			say STDERR "couldn't get height, width of $file\n$progname fatal error.";exit 1; 
		}
		my ($height,$width) = @p_size;
		sub make_divisible_by2 {
			my $n_width = shift;
			$n_width = int ( ($n_width /2 ) + .5 ); # fix error where width is odd number
			return $n_width * 2;
		}
		# we have both sizes, so correct the size by using the -size string from the arguments as a partial size
		if ($size =~ /(\d+)\D/) {  # right missing.  make new height
			my $p_width= $1; 
			my $ratio = $p_width / $width; 
			$size = "${p_width}x" . make_divisible_by2 $height * $ratio;
		} elsif ($size =~ /\D(\d+)/) { # left missing make new width
			my $p_height = $1; 
			my $ratio = $p_height / $height; 
			$size =  make_divisible_by2($width * $ratio) . "x${p_height}" ;
		} else { 
			die "$progname error bad size in pixels passed to -s"; 
		}
	}
	my @size = ( '-s', $size); @size = () unless $size;

	setlog $file;
	if ( $ss and $to ) { # try and adjust bitrate from "times" given.
		$ms =  to_seconds_conditional($to) *1000 - to_seconds_conditional($ss) *1000; 
	} elsif ($ss) {  
		$ms = $ms - to_seconds_conditional($ss) *1000; 
	} elsif($to) {  
		my $choptime = $ms - to_seconds_conditional($to) *1000;
		$ms = $ms - $choptime; 
	}
	my $b_opus = 80;  $b_opus = 95 if $h264; 
	my $bits_remainder = $eight - ($b_opus * $k * $ms /1000);
	my $b_vp9  = $bits_remainder / ( $ms /1000) ;
	if (31000 > $b_vp9 ) {
		say "$progname non-fatal error while trying to encode $file\nGiven size of $megabytes MiB, and assuming " . ($h264 ? "$b_opus kbps for AAC":"$b_opus kpbs for opus")  . ", only $b_vp9 bps were left for video, which isn't enough. (minimum of 31000)."; 
		next; 
	}
	use File::Spec::Functions "splitpath";
	my          $newfile  =  "$outdir/". $prefix. (splitpath $file)[2] if $outdir;
	$newfile  =  ( splitpath $file)[1] . $prefix. (splitpath $file)[2] unless $outdir;
	 
	my @extensions = qw( 3gp$ ogm$ divx$ rmvb$ wmv$ mov$ mpeg$ mpg$ avi$ mkv$ mp4$ m4v$ mkv$ webm$ );
	for my $ext (@extensions) {
		my $reach;
		eval { $reach=qr/$ext/;$newfile =~ s/$reach//;}; 
	}
	$newfile .= $h264 ? 'mp4':'webm';
	say("$progname: error outfile already exists. $newfile") , exit 1 if -e $newfile; 

if ($multi_pass and !$h264) {
my $comment = "	 For two-pass targeting an average bitrate, the target bitrate is specified with the -b:v switch:
ffmpeg -i input.mp4 -c:v libvpx-vp9 -b:v 2M -pass 1 -an -f null /dev/null && \
ffmpeg -i input.mp4 -c:v libvpx-vp9 -b:v 2M -pass 2 -c:a libopus output.webm";
	$" = ' '; 
	my $ret; $ret = system ( @e ,"ffmpeg","-hide_banner", "-i", $file,'-passlogfile',$logfile, split " ", "-c:v libvpx-vp9 @fps @size @ss @to -b:v $b_vp9 -pass 1 -an -f null /dev/null");
	($ret >> 8) or 
	do { $ret=system(@e, "ffmpeg","-hide_banner", "-i", $file, '-passlogfile',$logfile, "-c:v","libvpx-vp9",@realtime, @fps, @mono, @size, @ss, @to, "-b:v",$b_vp9,"-pass","2","-c:a","libopus","-b:a","${\($b_opus * $k)}", $newfile); $ret>>=8;}; 
	print( "$progname failed on ffmpeg\n"),exit if $ret;
} elsif(1) {

#	print(".\n.\n.\nwarning:  x264 tends to crash on durations less than 2.5s\n continue?"),getc  if $ms < 2600;
my $comment = "You can add -movflags +faststart as an output option if your videos are going to be viewed in a browser. This will move some information to the beginning of your file and allow the video to begin playing before it is completely downloaded by the
-preset slow
ffmpeg -y -i input -c:v libx264 -b:v 2600k -pass 1 -an -f null /dev/null && \
ffmpeg -i input -c:v libx264 -b:v 2600k -pass 2 -c:a aac -b:a 128k output.mp4";

# not what i want:.  "0:a:m:language:eng"
# 0:a:m:default is added because ffmpeg seems to select audio streams with the most channels, or streams or etc. see https://ffmpeg.org/ffmpeg.html#Stream-selection
# yes. seems to make stream mapping dumber. now it's trying to pass mjpeg streams to out, 
# ^^^^^^^ ok fixed it with 0:v:m:default
	my $ret; $ret = system ( @e ,"ffmpeg","-hide_banner","-i", $file, '-passlogfile',$logfile, "-map","0:v:m:default","-map","0:a:m:default",@mux_fix, "-c:v", "libx264", "-movflags", "+faststart", "-preset",  $preset, @fps, @size, @ss, @to, "-b:v", $b_vp9, "-pass", "1", @mono, "-c:a", "libfdk_aac", "-b:a", "${\($b_opus * $k)}", $newfile);
	($ret >> 8) or 
	do { $ret=system(@e, "ffmpeg","-hide_banner", "-i", $file, '-passlogfile',$logfile,  "-map","0:v:m:default","-map","0:a:m:default",@mux_fix, "-c:v","libx264","-movflags", "+faststart", "-preset",$preset, @fps, @size, @ss, @to, "-b:v",$b_vp9,"-pass","2",@mono, "-c:a","libfdk_aac","-b:a","${\($b_opus * $k)}", $newfile, '-y'); $ret>>=8;}; 
	print( "$progname failed on ffmpeg\n"),exit if $ret;
	}
elsif (0) {  # this was never useful on files that had bursts of high-bitrates.
# fix
	$b_vp9 *= .814; # the cpu-time parameter kind of defeats the whole intention of this program, honestly, since it makes the vp9 not care so much for bitrate param.  
	system @e, "ffmpeg","-hide_banner",  "-i", $file, "-c:v","libvpx-vp9",@realtime,"-b:v",$b_vp9,"-c:a","libopus","-b:a","${\($b_opus * $k)}", $newfile=~s/\.mp4$/\.webm/r;
}
	say "---- Completed OK ----";
	say $h264 ? "target bitrate was x264:${\int ($b_vp9/1000)} Kbps, aac:$b_opus Kbps":"target bitrate was vp9:${\int ($b_vp9/1000)} Kbps, opus:$b_opus Kbps";
	say "output file $newfile\nhas a size of ${\( (-s $newfile)/mb)} MB";
	$b_vp9 = int $b_vp9/1000;
	`bep` if check_exists_command 'bep';
	my $newsize = -s $newfile; 
	if (($newsize / mb) > $megabytes) { 
		print "$megabytes MB was specified but this size was exceeded!\n";
		print 'redo file with 1% larger margin for extra size? ';
		$_= readline STDIN; 
		if(/[yY]/) {  
			unlink $newfile; 
			clenup; 
			$inflation *= $inflation * (1 + 1/100); #1% 
			goto REDO
		}
	}
}
